### PR TITLE
fix: preserve line spacing and indentation on Google Docs paste

### LINKED ISSUE #2151: Preserve line spacing and indentation on Google Docs paste
### Summary

Preserve line spacing and paragraph indentation when pasting content from Google Docs into SuperDoc.

### Problem

Line spacing (single, 1.5x, double) and paragraph indentation are lost when pasting from Google Docs. Everything pastes as default spacing with no indentation.

### Repro

1. Create a Google Doc with different line spacings (single, 1.5, double) and indented paragraphs.
2. Copy the content and paste into SuperDoc.
3. All spacing is default and indentation is gone.

### Expected

Line spacing and indentation from pasted content are preserved in SuperDoc.

### Notes

`parseAttrs` reads `data-indent` and `data-spacing` JSON attributes (SuperDoc's internal format), but Google Docs uses inline CSS on `<p>` elements:

* **Line height:** `lineHeight: "1.2"` (single), `"1.8"` (1.5x), `"2.4"` (double)
* **Margins:** `marginTop`/`marginBottom` in pt
* **Indentation:** `marginLeft: "30pt"` (indented), `"60pt"` (double-indented)
* **Blockquote:** Google Docs sends `marginLeft: "30pt"` as a `<p>`, not a `<blockquote>` tag

The fix should extract `node.style.lineHeight`, `node.style.marginLeft`, `node.style.marginTop`, and `node.style.marginBottom` in `parseAttrs`, then convert them to `paragraphProperties.spacing` and `paragraphProperties.indent`.

**File:** `packages/super-editor/src/extensions/paragraph/helpers/parseAttrs.js`

[copy-paste-test.docx]()

---

**Want to work on this?** Check the [Contributing Guide](<https://github.com/superdoc-dev/superdoc/blob/main/CONTRIBUTING.md>) to get started. Comment on the GitHub issue to let us know you're picking it up.

---

**Want to work on this?** Check the [Contributing Guide](https://github.com/superdoc-dev/superdoc/blob/main/CONTRIBUTING.md) to get started. Comment on this issue to let us know you're picking it up.

*Ref: SD-1980*

### PR DESCRIPTION
**Pull request by gpardhivvarma**
## Summary

- Add CSS inline style fallback in `parseAttrs.js` so line spacing (`lineHeight`), paragraph spacing (`marginTop`/`marginBottom`), indentation (`marginLeft`), and first-line/hanging indent (`textIndent`) are preserved when pasting from Google Docs or other sources that use inline CSS instead of SuperDoc's `data-*` attributes
- Use a single `parseCssLength` helper backed by a `CSS_LENGTH_TO_PT` conversion map supporting `pt`, `px`, `in`, `cm`, `mm` — unrecognized units (`em`, `rem`, etc.) are safely ignored
- Use exact `72 / 96` ratio for px→pt conversion, matching `PX_PER_PT` in pm-adapter
- Correctly parse CSS `line-height` units: unitless and `%` values are stored as auto multipliers, while absolute lengths are stored as exact line spacing in twips
- Line spacing formula inverts pm-adapter's `normalizeLineValue` (`value * 1.15 / 240`) so values round-trip correctly
- Map positive `text-indent` to `indent.firstLine` and negative `text-indent` to `indent.hanging`
- Preserve explicit zero margins (`margin-top: 0`) as `0` twips to prevent the style-engine from applying non-zero defaults
- Fix pre-existing bug: skip `Number()` coercion for `lineRule` in `data-spacing` parsing to preserve the `'auto'` string value
- Data attributes still take priority, so existing DOCX paste behavior is unchanged

Closes #2151

## Test plan

- [ ] Paste from Google Docs with different line spacings (single, 1.5, double) and verify they are preserved
- [ ] Paste indented paragraphs from Google Docs and verify indentation is preserved
- [ ] Paste HTML with first-line and hanging indentation and verify correct rendering
- [ ] Paste HTML with percentage/px/pt/in/cm/mm values and verify correct conversion
- [ ] Paste HTML with explicit zero margins and verify no unintended spacing appears
- [ ] Paste from Word and verify existing `data-spacing`/`data-indent` behavior is unchanged
- [x] Run `pnpm test` — all parseAttrs tests pass (28/28)

### CODE REVIEW

**Comment by gpardhivvarma** [comment]
@caio-pizzol

**Comment by gpardhivvarma** [comment]
@codex review

**Comment by gpardhivvarma** [comment]
@codex review

**Comment by gpardhivvarma** [comment]
@codex review

**Comment by gpardhivvarma** [comment]
@codex review

File: packages/super-editor/src/extensions/paragraph/helpers/parseAttrs.js [hunk 1]
```diff
@@ -1,3 +1,23 @@
+const CSS_LENGTH_TO_PT = { pt: 1, px: 1 / 1.333, in: 72, cm: 28.3465, mm: 2.83465 };
```
Comment (caio-pizzol) [inline packages/super-editor/src/extensions/paragraph/helpers/parseAttrs.js]: `1 / 1.333 is 0.75018`, not `0.75`. use `72 / 96` - it's exact and matches `PX_PER_PT` in `pm-adapter/constants.ts`.

File: packages/super-editor/src/extensions/paragraph/helpers/parseAttrs.js [hunk 2]
```diff
@@ -32,6 +52,56 @@ export function parseAttrs(node) {
...
+  // CSS inline style fallback for spacing (e.g. Google Docs paste)
+  if (!spacing && node.style) {
+    const cssSpacing = {};
+
+    const lh = parseCssLength(node.style.lineHeight);
+    if (lh && lh.points > 0) {
+      if (lh.unit === '' || lh.unit === '%') {
+        // Unitless (1.5) or percentage (115%) → auto multiplier
+        const multiplier = lh.unit === '%' ? lh.points / 100 : lh.points;
+        cssSpacing.line = Math.round((multiplier * 240) / 1.15);
```
Comment (caio-pizzol) [inline packages/super-editor/src/extensions/paragraph/helpers/parseAttrs.js:66]: this inverts pm-adapter's `normalizeLineValue (value * 1.15 / 240)` so values round-trip correctly. two things:
(1) a comment explaining that would help - the 1.15 is non-obvious
(2) Google Docs uses 1.2 for "single spacing", so this produces 250 twips instead of the canonical 240. rendering is fine, but could matter for DOCX export.

File: packages/super-editor/src/extensions/paragraph/helpers/parseAttrs.test.js [hunk 3]
```diff
@@ -0,0 +1,237 @@
...
+describe('parseAttrs', () => {
+  describe('data-attribute parsing (existing behavior)', () => {
+    it('parses data-spacing JSON attribute', () => {
+      const node = createMockNode({
+        'data-spacing': JSON.stringify({ line: 360, lineRule: 'auto', before: 120, after: 80 }),
+      });
+      const result = parseAttrs(node);
+      expect(result.paragraphProperties.spacing).toEqual({
+        line: 360,
+        lineRule: NaN, // string values get Number() applied
```
Comment (caio-pizzol) [inline packages/super-editor/src/extensions/paragraph/helpers/parseAttrs.test.js]: pre-existing bug: the data-spacing path runs `Number()` on every key, turning 'auto' into `NaN`. this loses the line rule downstream. not your fault, but this test locks it in.

small fix: skip `Number()` for `lineRule`

File: packages/super-editor/src/extensions/paragraph/helpers/parseAttrs.js (hunk 1 above)
Comment (gpardhivvarma) [reply packages/super-editor/src/extensions/paragraph/helpers/parseAttrs.js]: Fixed — switched to `72 / 96` for exact conversion matching `PX_PER_PT`.

File: packages/super-editor/src/extensions/paragraph/helpers/parseAttrs.js (hunk 2 above)
Comment (gpardhivvarma) [reply packages/super-editor/src/extensions/paragraph/helpers/parseAttrs.js:66]: Added a comment explaining the `1.15` inversion from `normalizeLineValue`.

File: packages/super-editor/src/extensions/paragraph/helpers/parseAttrs.test.js (hunk 3 above)
Comment (gpardhivvarma) [reply packages/super-editor/src/extensions/paragraph/helpers/parseAttrs.test.js]: Fixed — `Number()` now skips `lineRule` so the `'auto'` string is preserved. Updated the test expectation accordingly.

**Comment by gpardhivvarma** [comment]
> @gpardhivvarma all three items from last round are addressed — `72 / 96` is exact, `lineRule` is preserved, and the `1.15` comment makes the inversion clear. no new issues in the incremental diff.
> 
> tested locally — CSS spacing values (line-height, margin-top/bottom) are being picked up and converted to twips correctly on Google Docs paste. looks good to merge.
> 
> note: `text-align` (center/right/justify) is not preserved on paste either, should be fixed on another PR

Will look into it and create a new PR

**Comment by harbournick** [comment]
:tada: This PR is included in **superdoc** v1.17.0

The release is available on [GitHub release](https://github.com/superdoc-dev/superdoc/releases/tag/v1.17.0)
